title: Risto Hietala
description: >
  Cool stuff about computers
baseurl: ""
#url: "http://localhost:4000" # for local jekyll
url: "http://www.hietala.org"
paginate:	2 # The number of posts to show per page on your homepage
name: "Risto Hietala"
markdown: kramdown
permalink: none
twitter_username: ristohietal
github_username: rhietala
future: true
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
